<h1>Construction</h1>

<table>
    <thead>
        <tr>
            <th>Building</th>
            <th>Level</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->buildings as $building): ?>
            <tr>
                <td><?= $this->escapeHtml($building->habitacion) ?></td>
                <td><?= $this->escapeHtml($building->nivel) ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
